[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[site]
bucket = "dist"
entry-point = "."

[functions]
directory = "functions"
node_compat = true

[env.production]
name = "matthewweb.com"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

# Cache settings for static assets
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

# Cache settings for HTML files
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=3600"

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()" 