[build]
command = "npm run build"
output_directory = "dist"

[build.environment]
NODE_VERSION = "20.9.0"
NPM_VERSION = "10.2.4"

[site]
bucket = "./dist"
entry-point = "."

[env.production]
name = "matthewweb-com"
workers_dev = true
route = "matthewweb.com/*"
zone_id = "your-zone-id"

[env.production.vars]
ENVIRONMENT = "production" 