# Cloudflare Pages configuration
name = "matthewweb"
compatibility_date = "2024-03-20"

[build]
command = "npm run build"
output_directory = "dist"

[site]
bucket = "./dist"

[env.production]
workers_dev = false
route = "matthewweb.com/*"

[env.production.vars]
NODE_ENV = "production" 