# Cloudflare Pages configuration for matthewweb.com
name = "matthewweb"
compatibility_date = "2024-03-20"

[build]
command = "npm run build"
output_directory = "dist"

[pages]
build_output_dir = "dist"
deployment_branch = "main"
custom_domain = "matthewweb.com" 